### ISSUE TITLE
Issue with new blog posts

### ISSUE THREAD

**Issue by davnastasi** [toubsen/wp-auto-more-tag#3]
Hi Toubsen,

This is Davide, Travis (Weston) suggested to reach out to you. 

I love the auto more tag wordpress plugin and I'd really like to keep using it but every time i upload a new blog post i need to manually "update" the plugin settings for the tag to be applied to the last piece of content. 

Can you please suggest a way to fix that? 

Best,
Davide

**Comment by anubisthejackle** [comment]
How long has this problem been happening? Did it start after installing new plugins / themes? Or maybe after a recent WordPress update?

**Comment by davnastasi** [comment]
It's been during the last couple of weeks, haven't rally done anything that
could conflict with in

On Saturday, May 23, 2015, Travis Weston notifications@github.com wrote:

> How long has this problem been happening? Did it start after installing
> new plugins / themes? Or maybe after a recent WordPress update?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toubsen/wp-auto-more-tag/issues/3#issuecomment-104892725
> .

## 

## 

Biz Dev @ Contentools http://contentools.com
+1 (415) 579-8272
 #500Strong http://500.co/contentools

Ps. _Boost_ your content marketing with Contentools
http://contentools.com/! Get *early access *at contentools.com.

**Comment by anubisthejackle** [comment]
Can you check which version of WordPress you're running, and also which version of the plugin?

**Comment by davnastasi** [comment]
Alright, I'm not on laptop now, I'll check that as soon as I get to it

On Saturday, May 23, 2015, Travis Weston notifications@github.com wrote:

> Can you check which version of WordPress you're running, and also which
> version of the plugin?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toubsen/wp-auto-more-tag/issues/3#issuecomment-104939553
> .

## 

## 

Biz Dev @ Contentools http://contentools.com
+1 (415) 579-8272
 #500Strong http://500.co/contentools

Ps. _Boost_ your content marketing with Contentools
http://contentools.com/! Get *early access *at contentools.com.

**Comment by davnastasi** [comment]
WP 4.2.2
Auto more tag 3.2.2

On Saturday, May 23, 2015, Davide Nastasi davide@contentools.com wrote:

> Alright, I'm not on laptop now, I'll check that as soon as I get to it
> 
> On Saturday, May 23, 2015, Travis Weston <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Can you check which version of WordPress you're running, and also which
> > version of the plugin?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/toubsen/wp-auto-more-tag/issues/3#issuecomment-104939553
> > .
> 
> ## 
> 
> ## 
> 
> Biz Dev @ Contentools http://contentools.com
> +1 (415) 579-8272
>  #500Strong http://500.co/contentools
> 
> Ps. _Boost_ your content marketing with Contentools
> http://contentools.com/! Get *early access *at contentools.com.

## 

## 

Biz Dev @ Contentools http://contentools.com
+1 (415) 579-8272
 #500Strong http://500.co/contentools

Ps. _Boost_ your content marketing with Contentools
http://contentools.com/! Get *early access *at contentools.com.

**Comment by anubisthejackle** [comment]
The plugin is a super simple setup. It ties into the `content_save_pre` filter, which should be run everytime your post is saved. I'll setup a test environment with that version of WP and AMT and see if I can duplicate the issue. I'd say on your side to try to disable individual plugins, and create test posts, to test to see if there is a conflicting plugin that's removing the more tag, or canceling out the content_pre_save filter.

**Comment by davnastasi** [comment]
Alright! I'll try that out, thanks a lot!

On Saturday, May 23, 2015, Travis Weston notifications@github.com wrote:

> The plugin is a super simple setup. It ties into the content_save_pre
> filter, which should be run everytime your post is saved. I'll setup a test
> environment with that version of WP and AMT and see if I can duplicate the
> issue. I'd say on your side to try to disable individual plugins, and
> create test posts, to test to see if there is a conflicting plugin that's
> removing the more tag, or canceling out the content_pre_save filter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toubsen/wp-auto-more-tag/issues/3#issuecomment-104940949
> .

## 

## 

Biz Dev @ Contentools http://contentools.com
+1 (415) 579-8272
 #500Strong http://500.co/contentools

Ps. _Boost_ your content marketing with Contentools
http://contentools.com/! Get *early access *at contentools.com.

**Comment by anubisthejackle** [comment]
I've pushed an update to the WordPress repo that should fix this. Also, given that this seems like a stale repository, I've switched the working repo back to my own:

http://github.com/anubisthejackle/wp-auto-more-tag/

If you'd like you can close the issue here and reopen it there.
